HZ_CUBE_TYPE_NORMAL = 1
HZ_CUBE_TYPE_CRY    = 2
HZ_CUBE_TYPE_MATCH  = 1
HZ_CUBE_TYPE_SELECT = 2

HZ_CUBE_COUNT = 7

HZBoardSizeX = 7
HZBoardSizeY = 7
HZChoseIconIndex = 21

HZ_NORMAL_TAG = 10
HZ_MATCH_TAG  = 30
HZ_SELECT_TAG = 40

GBackGroundWidth = 712
GBackGroundHeight = 1024

HZ_GRID_OFFSET_X = 5
HZ_GRID_OFFSET_Y = 100

HZ_GRID_WIDTH = 90

